name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    uses: actions/checkout@v3

    - name: Set up python
    uses: actions/setup-python@v4
    with:
      python-version:  '3.12'

    - name: Install project dependencies
    run: | 
      python -m pip install --upgrade pip
      pip install -r --no-cached-dir requirements.txt

    - name: Run tests
     run: |
       pytest -v

build:
  runs-on: ubuntu-latest
  needs: test

  steps: 
  - name: Checkout code
  - uses: actions/checkout@v3

  name: Set-up python
  uses: actions/setup-python@v4
  with: 
    python-version: '3.12'

  - name: Build docker image
   run: | 
     docker build -t laptop-scrapper .

  - name: Run the container
    run: |
      docker run -d -p 8000:8000 laptop-scrapper

  - name: Check app health
    run: curl -f http://localhost:8000 || exit 1

